### ISSUE TITLE
v2.0.0 seems to be broken in Windows?

### ISSUE THREAD

**Issue by craigb** [zeit/hpm#77] opened 2017-02-16 22:20 UTC
I just tried installing Hyper in Windows for the first time, and hpm search just brings up the help. 

<img src="https://raw.githubusercontent.com/matheuss/hpm/master/screenshot.gif?v=2" width="629">

Here's what I see:
```
❯ hpm search power
- Searching
  Usage: hpm [options] [command]

  Commands:

    d, docs, h, home               Open the npm page of a plugin
    f, fork                        Fork a plugin from npm into your ~/.hyper_
plugins/local
    help                           Display help
    i, install                     Install a plugin
    ls, list                       List installed plugins
    lsr, list-remote, ls-remote    List plugins available on npm
    s, search                      Search for plugins on npm
    u, uni, uninstall, rm, remove  Uninstall a plugin

  Options:

    -h, --help     Output usage information
    -v, --version  Output the version number
```

**Comment by crutchcorn** [comment] 2017-02-17 18:38
Duplicate of #72

**Closed** 2017-03-05 18:17 UTC
